# Generated by Django 5.2.4 on 2025-07-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_experience_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
