# Generated by Django 5.2.4 on 2025-07-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blindness_Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='category_breakdown',
            field=models.JSONField(default=dict),
        ),
    ]
